apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chat2db-encryption-key
  namespace: chat2db
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv-cluster-secret-store
  target:
    name: chat2db-encryption-key
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        encryption.key: "{{ .encryptionKey }}"
  data:
    - secretKey: encryptionKey
      remoteRef:
        key: secret/chat2db-community-encryption-key
