apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chat2db-hazytrade-datasource
  namespace: chat2db
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv-cluster-secret-store
  target:
    name: chat2db-hazytrade-datasource
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        key: secret/chat2db-hazytrade-ro-password
    - secretKey: ca.crt
      remoteRef:
        key: secret/hazy-trade-postgres-ca-crt
