apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chat2db-openai-proxy
  namespace: chat2db
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv-cluster-secret-store
  target:
    name: chat2db-openai-proxy
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: api-key
      remoteRef:
        key: secret/openai-key-proxy-client-api-key
